### ISSUE TITLE
Design website

### ISSUE THREAD

**Issue by xla** [mmmh-studio/validator#8]
_From @onurakpolat on July 16, 2018 14:48_

_Copied from original issue: mmmh-studio/iteration#4_

**Comment by xla** [comment]
@onurakpolat which direction would you prefer?

![ce6e6e9e-7032-49fc-af4a-c078750f91ef](https://user-images.githubusercontent.com/1585/42886005-c6f651b6-8aa2-11e8-89c0-4c407f7102db.png)
![2bc89c49-2a9b-4b99-a4cf-e504c4f80bac](https://user-images.githubusercontent.com/1585/42886006-c71241f0-8aa2-11e8-9f7b-a8b2ee240e75.png)
![628e5b70-7e62-4bf5-bd14-1e5ec9f0d8ce](https://user-images.githubusercontent.com/1585/42886007-c72ceb40-8aa2-11e8-96f4-a9e29a8d5f60.png)
![6d0558cb-bf71-49d4-904c-bb8e6b1d58d5](https://user-images.githubusercontent.com/1585/42886008-c74e569a-8aa2-11e8-9217-ee6f9763a1b7.png)

**Comment by xla** [comment]
_From @onurakpolat on July 18, 2018 13:59_

4.

Most clean, simple and yet playful.

**Comment by xla** [comment]
@onurakpolat Tried a more reduced approach with overview of planned Validators with their respective progress and call to sction to delegate. Goal was to fit all info in a single view as I don't expect a lot of content. The design will live of clean typography. Thoughts?

![6646ec0a-99c7-4dac-9955-f7d56dd6b99d](https://user-images.githubusercontent.com/1585/43301577-1678ad78-9134-11e8-9000-e0192f93c748.png)

**Comment by xla** [comment]
_From @onurakpolat on July 27, 2018 11:41_

Love it. Clean and simple everything on one page...
Font is something we can play around with.

**Comment by xla** [comment]
Iterated further on the design (fonts, colors, progress), if you dig it I gonna share the styleguide infos.

![42f02a5a-d6a8-4100-ab4f-8f0b689be06c](https://user-images.githubusercontent.com/1585/43358862-9621fbbe-9266-11e8-935c-ccc0712d44e5.jpeg)

**Comment by xla** [comment]
_From @onurakpolat on July 28, 2018 18:16_

Really f'cking awesome. Dig it hard. A couple small things that I would change:

* Line-height in paragraph a bit bigger
* Consistent color or greyscale for progress bars (looks a bit too bunt)
* Normalize logo sizes (they're big vs. small)

What I really like:

* Title font
* Overall slim design

**Comment by xla** [comment]
@onurakpolat Adressed, lemme know about last touches from ur end.

![92e7a193-1d39-4b81-b19f-4476f3ee3c29](https://user-images.githubusercontent.com/1585/43360732-6141ee4e-928a-11e8-98c6-e26cd69b3eb2.jpeg)

**Comment by xla** [comment]
_From @onurakpolat on July 30, 2018 9:8_

Like it as is. Looks great. Will start implementing.

**Comment by xla** [comment]
Until proper styleguide is in place:

### color
base color (top logo, paragraphs, progress bar background): rgb(25, 52, 65)
secondary color (section headings, progress bar foreground): rgb(62, 96, 111)

### typography

- h1: Sorts Mill Goudy Italic 56
- h2: Sorts Mill Goudy 28
- p: Raleway Regular 14

Google fonts embed:

``` html
<link href="https://fonts.googleapis.com/css?family=Raleway|Sorts+Mill+Goudy:400,400i" rel="stylesheet">
```

``` css
font-family: 'Sorts Mill Goudy', serif;
font-family: 'Raleway', sans-serif;
```

### grid

- cols: 12
- width: 80px
- gutter: 20px
- top:  50px
- bottom: 50px
- left: 80px
- right: 80px

**Comment by oxnr** [comment]
done.
![image](https://user-images.githubusercontent.com/1712926/44792280-d2d51900-aba3-11e8-9500-0914ffc36d90.png)
