### ISSUE TITLE
Define GCP environment

### ISSUE THREAD

**Issue by xla** [mmmh-studio/validator#9]
_From @onurakpolat on July 16, 2018 14:49_

_Copied from original issue: mmmh-studio/iteration#5_

**Comment by xla** [comment]
Was attempt were futile as the virtual credit card wasn't accepted. Currently blocked on a real credit card so the billing account can be re-opened, which is necessary to create any kind of resource

**Comment by oxnr** [comment]
@xla 

As discussed, lets:

* Define a Kubernetes config for Polkadot
* Automate setup and creation with Terraform

That would finalize the env ticket for me, even tho the terraform automation work could be separated.
